### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by tommhuth** [colebemis/feather#1]
This is a great set of icons, but I do miss one thing:

Boxes and circles that equate in size, with and without checkmark/dot. This would make them usefull for radio/checkbox button replacements.

**Comment by colebemis** [comment]
Thanks for the suggestion! Look out for those icons in the next version.

**Comment by Rodrigo-Ludgero** [comment]
I agree with @tommhuth, this is a great set of icons, but i am missing a empty circle and empty square with equal size for using like a checkbox and radio buttons.
Thanks for share.
:+1:

**Comment by 89abdul** [comment]
I agree with @Rodrigo-Ludgero,
Its really great sets of Icons but there is no icons like home, phone, social icon etc...
Thanks for nice icons.

**Comment by supertag-codeship** [comment]
Thanks for the amazing icon set. But I really want to have edit icon. Of course, I can use `icon-cog` instead, but I already use it another place, so it will be confusing.

**Comment by tyomo4ka** [comment]
Thanks for the amazing icon set. But I really want to have edit icon. Of course, I can use `icon-cog` instead, but I already use it another place, so it will be confusing.

**Comment by tyomo4ka** [comment]
BTW for those who wants to use bower to install these awesome icons, you can simply add this to your bower.json:

`    "feather": "git@github.com:colebemis/feather#master"`

**Comment by colebemis** [comment]
`circle`, `square`, `home`, `phone`, `edit` and social icons have all been added 👍

**Comment by tyomo4ka** [comment]
@colebemis Thank you for this! It looks perfect :)
