### ISSUE TITLE
Icon Request: TV

### ISSUE THREAD

**Issue by chrismessina** [colebemis/feather#106]
While there's an icon for Airplay and Cast, there isn't one for a standard TV. 

Here's Facebook's icon:

![fb_glyphs_television_24 3x](https://user-images.githubusercontent.com/22610/26954378-7586b618-4c64-11e7-8ea0-0c495f56c721.png)

**Comment by chrismessina** [comment]
I took a stab.

[TV.svg.zip](https://github.com/colebemis/feather/files/1062642/TV.svg.zip)

**Comment by colebemis** [comment]
This looks pretty similar to the current `monitor` icon. Maybe this will cover your use case? https://github.com/colebemis/feather/blob/master/icons/core/monitor.svg

**Comment by chrismessina** [comment]
Ha, wow. Yeah, I guess that'll work! Maybe rename as "Screen" or "TV"? :)

**Comment by drewish** [comment]
I think screen as a name would be more descriptive. It might be easier to discover with its current name if it was moved it into the Photo And Video section.

**Comment by chrismessina** [comment]
+1

**Comment by tristinDLC** [comment]
If you want more of a "TV" feel, I think altering the `monitor` icon to remove the stand and include rabbit ears might be a nice touch. Rabbit ears aren't really a thing anymore, but are still pretty iconic as far as TV recognition goes IMHO.
