### ISSUE TITLE
How do I change color of the icons?

### ISSUE THREAD

**Issue by nilsi** [colebemis/feather#109]
Hi, nice job!

Whats the best way to integrate them into my project? Currently I just do like this:

```
<img class="ui mini circular image" src="/icons/core/plus.svg" alt="Add product">
```

But I need to change the stroke color, which I don't know if it's possible like this. Should I use the SVG element instead?

**Comment by colebemis** [comment]
Using `img` won't let you change anything about the SVG. If it doesn't make things too messy, I would just copy the inline SVG directly into the code. This will allow you to change any attribute with CSS.  

Here's a great video explaining the different ways SVGs can be used and the pros and cons of each approach: https://www.youtube.com/watch?v=af4ZQJ14yu8

Hope this helps.

**Comment by nilsi** [comment]
Thanks I will go with that approach!

**Comment by InstanceOfMichael** [comment]
Run a bash script with the following contents after `npm install` but before webpack (or other build tool).
```
for i in node_modules/vue-feather-icon/components/*; do
    # egrep -o 'stroke="#000(000){0,1}"' $i
    # echo 'before';
    # egrep -o 'stroke="#[0-9a-zA-Z]*"' $i
    sed -i 's/stroke="#000"/stroke="#fff"/' $i
    # echo 'after';
    egrep -o 'stroke="#[0-9a-zA-Z]*"' $i
done
```

My example assumes you want it white (`#fff`) instead of black (`#000`).
