### ISSUE TITLE
Add Sketch File

### ISSUE THREAD

**Issue by sweetyams** [colebemis/feather#115]
I'm not sure if you created these in Sketch - but I added them into a new sketch file with more granular organization - might be helpful for people? feel free to delete this file if you would prefer to keep the core assets for your own use.

https://www.dropbox.com/s/lyuk4zcorfkgfi9/feather.sketch?dl=0

Sincerely
Willem

**Comment by colebemis** [comment]
Thanks for doing that @sweetyams! I don't think I'll include a Sketch file because it requires too much maintenance. I'd prefer to keep the `icons` directory as the single source of truth for Feather.

P.S. These icons were actually created in Illustrator.

**Comment by sweetyams** [comment]
Sounds good!

ps the icons are BEAUTIFUL. ⭐️

**Comment by sebastiaanluca** [comment]
Thanks for the Sketch file @sweetyams! Way easier than copying each SVG file to Sketch and creating a symbols from it.

**Comment by sweetyams** [comment]
@sebastiaanluca I actually have an updated version I have been using - It has each icon separated out with a fill layer and mask so it is super easy to use in Sketch with overrides.

https://www.dropbox.com/s/yv9vl9xaqa3qagv/Feather%20Icons.sketch?dl=0


![Symbol use](http://g.recordit.co/Q63ANL1fHF.gif "Symbol in Use")

**Comment by sebastiaanluca** [comment]
You're a lifesaver, thank you! I'm using icons exactly the same way, great technique.
