### ISSUE TITLE
Icon request: GitLab

### ISSUE THREAD

**Issue by acisternino** [colebemis/feather#119]
An icon for [GitLab](https://www.gitlab.com/).

Some examples [here](https://about.gitlab.com/press/).

**Comment by Swizz** [comment]
This is a global question for all the logos request, because I am not a lawyer : this is legal to modify a company official logo to match your style ?

**Comment by acisternino** [comment]
IANAL too but in this particular case I think modifications are allowed.

The actual [code repository](https://gitlab.com/gitlab-com/gitlab-artwork/) for the logos says that they are licensed under a [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.
