### ISSUE TITLE
the info icon missing the superscript dot

### ISSUE THREAD

**Issue by bluemix** [colebemis/feather#123]
Hello dear,
I am using Affinity Photo v1.5.2 on macOS Sierra 10.12.5 (16F73).
When I want to use the `info` svg icon in Affinity Photo,
I have it, but missing the superscript dot (or the title).

![info-2](https://user-images.githubusercontent.com/3332274/27330169-f20a2c82-55c0-11e7-921a-e807f06c9cf0.png)

Although, I opened the svg icon in Opera browser, and it shows 
the superscript dot.
I just want you to be informed.
Thanks a lot for your icons 👍

**Comment by tristinDLC** [comment]
I have never used Affinity as I have the Adobe suite, so maybe Affinity handles single points with stroke weights different than other programs. If you still need an SVG of that icon, here is an expanded version (it's scalable like any SVG, but the line paths are no longer editable). You shouldn't have any issues using this version with whatever program can handle SVGs. 
[info.zip](https://github.com/colebemis/feather/files/1115887/info.zip)

**Comment by bluemix** [comment]
ok, thank you :)
