### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by MarcAllenDK** [colebemis/feather#125]
> If you'd like to request an icon, please provide the following information:
> - Offline
> - To show when there's no wifi signal 
> - screenshots of similar icons
https://thenounproject.com/term/disconnected/625410/

>
> Please create one issue for each icon request.

**Comment by tristinDLC** [comment]
Not the original designer, but was working on some additional icons to contribute. Here should be an icon that fits the same aesthetic. Let me know if it works for you. 
[wifi-off.zip](https://github.com/colebemis/feather/files/1114912/wifi-off.zip)
