### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by MarcAllenDK** [colebemis/feather#126]
> If you'd like to request an icon, please provide the following information:
> - Settings
> - To be able to show the user where to get to settings-menu
> - https://thenounproject.com/search/?q=settings&i=1098666
>
> Please create one issue for each icon request.

**Comment by tristinDLC** [comment]
Not the original designer, but was working on some additional icons to contribute. Here should be an icon that fits the same aesthetic. Let me know if it works for you.
[settings-slider.svg.zip](https://github.com/colebemis/feather/files/1114925/settings-slider.svg.zip)

**Comment by MarcAllenDK** [comment]
Thank you so much :-)

___

Venlig hilsen / Kind regards

Allan Marcuslund
VP Product Design

Mobile: +45 3171 2525
Email: am@digizuite.com

Let's connect on LinkedIn<https://www.linkedin.com/in/allanmarcuslund/>

[ttps://i.xink.io/Images/Get/N91777/s.png]<https://twitter.com/digizuitedam>[ttps://i.xink.io/Images/Get/N91777/s3.png]<https://www.linkedin.com/company/digizuite>[ttps://i.xink.io/Images/Get/N91777/s7.png]<https://www.facebook.com/digizuite>[ttps://i.xink.io/Images/Get/N91777/s5.png]<https://www.instagram.com/digizuite/>[ttps://i.xink.io/Images/Get/N91777/s2.png]<https://www.youtube.com/user/TheDAMvideos>

Digizuite A/S
Ryttergade 12, 1. | 5000 Odense C
Tel: +45 7022 2095

www.digizuite.com<http://www.digizuite.com> | www.damforsitecore.com<http://www.damforsitecore.com>

[gizuite logo]<http://www.digizuite.com/>
