### ISSUE TITLE
Icon Request - Warning Triangle

### ISSUE THREAD

**Issue by sittim** [colebemis/feather#127]
> If you'd like to request an icon, please provide the following information:
> - Warning - Triangle
> - Notify that there is an issue
> - screenshots of similar icons
>
![selection_114](https://user-images.githubusercontent.com/8825037/27435862-6b025f68-572b-11e7-9827-bc464ee69e92.png)

> Please create one issue for each icon request.

**Comment by alexantr** [comment]
@sittim check `alert-triangle`
