### ISSUE TITLE
Is it possible to convert strokes to fills?

### ISSUE THREAD

**Issue by Soreine** [colebemis/feather#129]
Hi! Awesome project. I am watching it closely and planning on using it.
My main use would be to pack some icons in a font, or to integrate them in my React app the same way than [`react-icons`](https://github.com/gorangajic/react-icons).
However, both of these approaches requires the SVG to not use strokes. Strokes need to be converted to path. For example, I had to convert `arrow-up` manually with Inkscape in order to integrate it.

Could this be done for the past and upcoming icons?

**Comment by Swizz** [comment]
Take a look at https://github.com/colebemis/feather/issues/104 especially https://github.com/colebemis/feather/issues/104#issuecomment-307161432

**Comment by Soreine** [comment]
Oops, I did not search for the right keywords. Thank you.
And thanks for the insights about strokes.
