### ISSUE TITLE
Pencil/Edit Icon Request

### ISSUE THREAD

**Issue by teemyster** [colebemis/feather#130]
Requested information is as follows::
 - Icon Name: "pencil" or "edit"
 - Use Case: An easy-to-read way of editing an item/piece of data, e.g. on pencil icon click, edit mode is initiated for a list item
 - Screenshots of similar icons: http://fontawesome.io/icon/pencil/

**Comment by alexantr** [comment]
@teemyster check `edit`, `edit-2` or `edit-3`
