### ISSUE TITLE
No links exist in colebemis.com/feather/

### ISSUE THREAD

**Issue by reblws** [colebemis/feather#141]
Just a heads up, all the download and icon links on http://colebemis.com/feather/ return 404s.

This was pretty confusing since colebemis.com/feather is the first result on google over the alternative https://feather.netlify.com/ link.

**Comment by colebemis** [comment]
Oops. Thanks for the heads up! I'll have to redirect colebemis.com/feather to feathericons.com. Do you happen to know how to set up a redirect with GitHub pages?

**Comment by reblws** [comment]
This [github help page](https://help.github.com/articles/redirects-on-github-pages/) suggests using this jekyll extension to help with redirects:
https://github.com/jekyll/jekyll-redirect-from

**Comment by colebemis** [comment]
Fixed! colebemis.com/feather should redirect to feathericons.com now.
