### ISSUE TITLE
Icon Request: Filter/sliders icon

### ISSUE THREAD

**Issue by cindehw** [colebemis/feather#144]
For filtering on websites, shopping lists, etc. 

![image](https://user-images.githubusercontent.com/23015321/27887703-121b9b28-61b0-11e7-90ec-5f1690116daf.png)

**Comment by alexantr** [comment]
Is it similar to new [sliders](https://feathericons.com/node_modules/feather-icons/dist/icons/sliders.svg) icon?

**Comment by cindehw** [comment]
Oh lmao I didn't see that nvmd
