### ISSUE TITLE
Changelog link is broken

### ISSUE THREAD

**Issue by chrismessina** [colebemis/feather#147]
The link in the footer of the homepage links here, which is a 404:

https://github.com/colebemis/feather/blob/gh-pages/CHANGELOG.md

![feather_ _simply_beautiful_open_source_icons](https://user-images.githubusercontent.com/22610/28047407-99e830f6-659e-11e7-8ead-18b1f4a24b5c.png)

**Comment by colebemis** [comment]
Thanks for letting me know! All the links should work now 👍
