### ISSUE TITLE
Icon request: help

### ISSUE THREAD

**Issue by alexantr** [colebemis/feather#15]
Icon name: help
Similar to "info" icon
![ic_help_outline_black_24dp](https://cloud.githubusercontent.com/assets/4941848/26650081/001ee7ec-4651-11e7-9f84-49e5575afbce.png)

**Comment by colebemis** [comment]
Thanks so much for creating all these icon requests @alexantr! Really helps me prioritize the work. Keep it up 😃

**Comment by thiagotomasi** [comment]
Hey, @alexantr and @colebemis here is my proposal to the 'help' icon: ![help](https://user-images.githubusercontent.com/4387026/28334877-34a26e74-6c05-11e7-926f-feaae98b32cc.png)
Let me know if you guys have any comments or feedback. 😄 

File: [help.zip](https://github.com/colebemis/feather/files/1157005/help.zip)
