### ISSUE TITLE
Icon request: Shopping cart icon

### ISSUE THREAD

**Issue by gyanl** [colebemis/feather#155]
> - icon name : shopping cart
> - at least one use case : to show your cart on an e-commerce website
> - screenshots of similar icons : 
![image](https://user-images.githubusercontent.com/9626697/28358984-6a658f26-6c8e-11e7-85ab-435bb04fab75.png)

**Comment by Swizz** [comment]
Dupplicate #20 #79

**Comment by gyanl** [comment]
Oops, my bad. Closing this issue.
