### ISSUE TITLE
Icon Request: Broken Link

### ISSUE THREAD

**Issue by Zhouzi** [colebemis/feather#173]
* Name: Broken Link / Link Broken
* Use case: signal broken links in a document
* Screenshot:

![](https://d30y9cdsu7xlg0.cloudfront.net/png/11788-200.png)

![](https://d30y9cdsu7xlg0.cloudfront.net/png/97622-200.png)

**Comment by su-narthur** [comment]
An icon like this could also be used to signify unlinking two items or removing a hypertext link.

![](https://cdn1.iconfinder.com/data/icons/seo-9/500/SEO_communication-512.png)

**Comment by jsejcksn** [comment]
The action lines are a must for this one.

**Comment by alexantr** [comment]
Please see #26

**Comment by Zhouzi** [comment]
Thanks @alexantr, definitely related! I didn't think to search for "unlink" 👍
