### ISSUE TITLE
Required files for a browser

### ISSUE THREAD

**Issue by extend1994** [colebemis/feather#178]
Hi!  I am a member from CDNJS and recently in charge of the process of adding feather-icons (we use npm as the source).
I would like to check which files does a user need to use feather-icons.
For the versions v3.0.0 ~ v3.2.2, I tested with https://github.com/colebemis/feather/blob/master/examples/index.html which only include feather.min.js and remove `icons` folder and `icons.json` on purpose. The result is that I can use icons correctly. My question is that do me need `icons` folder and `icon.json`?
For the versions v2.1.0 ~ v2.4.0, can we use these versions on a browser? If yes, could you tell me which files should we host?
Thank you.
BTW, You can see the progress in https://github.com/cdnjs/cdnjs/pull/11764 😃

**Comment by colebemis** [comment]
When using Feather on the client-side, `dist/feather.min.js` or `dist/feather.js` is all you need to get it working. `icons.json` is used to build `feather.min.js` and `feather.js` but is not necessary for production. The `icons` directory is not needed when using Feather in the browser. `v2+` was not designed to be used in the browser so there are no files to host.

Thanks for doing this! I'm excited to see this happen 👍

**Comment by extend1994** [comment]
@colebemis Thanks a lot! I believe we can host it soon after getting you clear response  💪 I will let you know here after the pull request is merged 😉

**Comment by extend1994** [comment]
@colebemis Thanks a lot! I believe we can host it soon after getting you clear response 💪 I will let you know here after the pull request is merged 😉
