### ISSUE TITLE
Icon Request: GitHub Logo

### ISSUE THREAD

**Issue by kurisubrooks** [colebemis/feather#19]
Useful for websites listing social links

Might have some trouble implementing Feather's overall style with this one as the border would have to be quite thin...

![image](https://cloud.githubusercontent.com/assets/6291467/26650675/85493a3a-468d-11e7-97f0-17f9d502e292.png)

**Comment by colebemis** [comment]
I've been wanting to add the GitHub logo for a while but can't seem to fit it into Feather's style constraints. I'll keep working on it though. Thanks for the suggestion!

**Comment by alexantr** [comment]
Variants from Icon8
![github-100](https://cloud.githubusercontent.com/assets/4941848/26651140/6ccdab82-4654-11e7-8136-5555e3bdc512.png)
![github-96](https://cloud.githubusercontent.com/assets/4941848/26651144/6ee2680e-4654-11e7-9f1d-18b103024207.png)

**Comment by kurisubrooks** [comment]
Love that 2nd icon!!

**Comment by colebemis** [comment]
Added to the `v2.2.0` branch (https://github.com/colebemis/feather/blob/v2.2.0/icons/logos/github.svg) :octocat:
