### ISSUE TITLE
Icon Request: Question Mark

### ISSUE THREAD

**Issue by sweetyams** [colebemis/feather#190]
Name: Question mark
Use: For denoting help or more information
Screenshots
<img width="145" alt="screenshot 2017-09-26 09 36 29" src="https://user-images.githubusercontent.com/1238170/30863204-73f63da6-a29e-11e7-9954-c3e3414fba6a.png">

**Comment by colebemis** [comment]
We already have`help-circle` 😄 https://github.com/colebemis/feather/blob/master/icons/help-circle.svg

**Comment by sweetyams** [comment]
Oh badass - I must have grabbed an early version that didn't have it - thanks!!
