### ISSUE TITLE
Icon Request: Heart Fill

### ISSUE THREAD

**Issue by nmdias** [colebemis/feather#205]
**icon name**: heart-fill
**use case**: Convey state change. e.g a user that favourites a news feed.
**screenshot**: The exact same `heart` icon in feather, just filled.

![heart-fill](https://user-images.githubusercontent.com/2228069/31579493-a42760aa-b12f-11e7-8314-ad79a868b93e.png)

Is this possible? Thank you 🙏

**Comment by colebemis** [comment]
See https://github.com/colebemis/feather/issues/48#issuecomment-305956722
