### ISSUE TITLE
Icon Request: Bookmark Fill

### ISSUE THREAD

**Issue by nmdias** [colebemis/feather#206]
**icon name**: bookmark-fill
**use case**: Convey state change. e.g a user that bookmarks an article from a news feed.
**screenshot**: The exact same `bookmark` icon in feather, just filled.

![bookmark-fill](https://user-images.githubusercontent.com/2228069/31579519-00da1d06-b130-11e7-9f31-5fc2c6215374.png)

And another one.. Thank you. 🙏

**Comment by alexantr** [comment]
colebemis about filled icons https://github.com/colebemis/feather/issues/48#issuecomment-305956722

**Comment by colebemis** [comment]
Thanks for the suggestion! However, I'm going to close this issue for the reasons stated in https://github.com/colebemis/feather/issues/48#issuecomment-305956722
