### ISSUE TITLE
Elm + feather

### ISSUE THREAD

**Issue by 1602** [colebemis/feather#211]
First of all, thanks for the great set of icons, in my opinion this is simply the best from what we have now. Great job!

I use these icons in elm, via embedding of svg. My usual workflow looks like this:

1. go to https://feathericons.com/
2. find icon and download .svg file
3. grab source of .svg file and paste it into https://mbylstra.github.io/html-to-elm/
4. fix resulting elm code (generated code is a bit outdated).
5. hooray, icon is ready to use in elm app.

After repeating these steps 1-5 several times I decided to automate it a bit and generate resulting elm code using JS api of feathericons. So I built https://1602.github.io/elm-feather-icons/ for my own convenience, but before I share it with anybody else from elm community I wanted to confirm with author that this is okay to use feathericons like this.

**Comment by colebemis** [comment]
This is awesome! 🎉🎉🎉 Nice work. Feel free to share 👍

**Comment by 1602** [comment]
Yey! Thank you @colebemis!

**Comment by colebemis** [comment]
@1602 Feel free to open a pull request to add your project to the `Related Projects` section of the README: https://github.com/colebemis/feather#related-projects

**Comment by 1602** [comment]
Will do. I'm currently working on getting official package published in registry (http://package.elm-lang.org/) once it is published I will submit PR.

**Comment by 1602** [comment]
Unrelated, your mail server seems to be offline :(

![image](https://user-images.githubusercontent.com/184172/45680865-f6044000-bb33-11e8-9de4-4aee44dc220a.png)
