### ISSUE TITLE
Icon request: movie

### ISSUE THREAD

**Issue by alexantr** [colebemis/feather#22]
Icon name: movie or film
Examples:
![film-96](https://cloud.githubusercontent.com/assets/4941848/26653497/013db92c-465c-11e7-822d-841596374f9d.png)
![movie-96](https://cloud.githubusercontent.com/assets/4941848/26653509/0810e2f6-465c-11e7-85c6-b26dc2c410ce.png)
![movie-100](https://cloud.githubusercontent.com/assets/4941848/26653514/095642dc-465c-11e7-883c-e8d85c235173.png)
![ic_theaters_black_24dp](https://cloud.githubusercontent.com/assets/4941848/26653528/0eaf42a6-465c-11e7-8851-bfc3f24d6cc5.png)

**Comment by colebemis** [comment]
Added to the `v2.2.0` branch (https://github.com/colebemis/feather/blob/v2.2.0/icons/photo-and-video/film.svg) 👍
