### ISSUE TITLE
RFC: Feather v4 Node API

### ISSUE THREAD

**Issue by colebemis** [colebemis/feather#222]
Proposal
---

I'm planning to update the node api for Feather in v4. Here's a usage example for the proposed api:

```js
import feather from 'feather-icons'

feather.icons.x
// {
//    name: 'x',
//    contents: '<line ... /><line ... />`,
//    tags: ['cancel', 'close', 'delete', 'remove'],
//    attrs: {
//      class: 'feather feather-x',
//      xmlns: 'http://www.w3.org/2000/svg',
//      width: 24,
//      height: 24,
//      viewBox: '0 0 24 24',
//      fill: 'none',
//      stroke: 'currentColor',
//      'stroke-width': 2,
//      'stroke-linecap': 'round',
//      'stroke-linejoin': 'round',
//    }
// }

feather.icons.x.toSvg()
// <svg class="feather feather-x" ...><line ... /><line ... /></svg>

feather.icons.x.toSvg({ class: 'foo bar', 'stroke-width': 1, color: 'red' })
// <svg class="feather feather-x foo bar" stroke-width="1" color="red" ...><line ... /><line ... /></svg>
```

### Notable Changes
* Each icon in the `feather.icons` object is now an `Icon` object with a `name`, `contents`, `tags` and `attrs` property.
* `toSvg()` is a method on each `Icon` object instead of a top-level method:
```
feather.toSvg() --> feather.<name>.toSvg()
```

Link to the current API for reference: https://github.com/colebemis/feather/blob/master/README.md#api-reference

> Inspiration for the API change came from [GitHub Octicons](https://github.com/primer/octicons/tree/master/lib/octicons_node)

Benefits
---

### Search

Each `Icon` in the `feather.icons` object has a `name` and `tags` property which will allow us to implement more powerful search on [feathericons.com](https://feathericons.com).

### Components

Each `Icon` in the`feather.icons` object has an `attrs` property which will make creating components for Feather in any framework a lot simpler. Here's an example of a simple Feather `Icon` React component: 

```jsx
import React from 'react'
import classnames from 'classnames'
import { icons } from 'feather-icons'

import attrsToProps from './attrs-to-props'

export default ({ name, ...props }) => (
  <svg 
    { ...attrsToProps(icons[name].attrs) }
    { ...props }
    { ...{ className: classnames(icons[name].attrs.class, props.className) } } 
    dangerouslySetInnerHTML={{ __html: icons[name].contents }} 
  />
)
```

Feedback
---
What do you think of this proposed API? Are there any downsides I haven't considered? I'm going to leave this RFC issue open for a week to allow us to discuss this API change.

**Comment by danielbeardsley** [comment]
Sounds good to me. I think Github's Octicon structure is a fine thing to model it after.

**Comment by danielj41** [comment]
This looks reasonable to me. :)

I'd suggest adding a `toString` method to the `Icon` class for backwards compatibility.

```js
el.innerHTML = feather.icons.x // is a string in v3
el.innerHTML = feather.icons.x // will implicitly call `toString` in v4
```

I think you could also `console.warn('deprecated')` if you try to call the old `feather.toSvg` in a development build.
