### ISSUE TITLE
Icon Request: Filled Bookmark

### ISSUE THREAD

**Issue by knoan** [colebemis/feather#224]
- icon name / bookmark-filled
- use case / icon for toggle buttons in conjunction with https://feathericons.com/node_modules/feather-icons/dist/icons/bookmark.svg
- screenshots of similar icons 
![screen shot 2017-11-18 at 09 16 45](https://user-images.githubusercontent.com/6105462/32978390-bf070b96-cc41-11e7-86b6-e837ef5006e6.png)

See also

- Icon Request: Filled circle #156
- Icon Request: Filled Hearth #225

**Comment by colebemis** [comment]
Thanks again for the suggestion! However, I'm going to close this for the reason I explained on your other issue https://github.com/colebemis/feather/issues/225#issuecomment-345473232
