### ISSUE TITLE
Icon Request: Filled Hearth

### ISSUE THREAD

**Issue by knoan** [colebemis/feather#225]
- icon name / hearth-filled
- use case / icon for toggle buttons in conjunction with https://feathericons.com/node_modules/feather-icons/dist/icons/hearth.svg
- screenshots of similar icons 
![screen shot 2017-11-18 at 09 17 05](https://user-images.githubusercontent.com/6105462/32978415-23bb14f6-cc42-11e7-9028-ba45ca549b37.png)

See also

- Icon Request: Filled circle #156
- Icon Request: Filled Bookmark #224

**Comment by colebemis** [comment]
Thanks for the suggestion! However, I'm going to close this issue for the reasons stated in https://github.com/colebemis/feather/issues/48#issuecomment-305956722:

> One of the guiding principles of Feather is that all icons use a 2px stroke with no fill. This creates consistency. Having a filled star would break this pattern and wouldn't fit in with the rest of the set. For that reason, I don't think it's a good idea to add it.

>That being said, I realize that there are valid use cases for a filled heart. The good news is that SVGs are very flexible and can be used in a variety of ways. It wouldn't be hard for anyone to add a `fill` to the heart outline if they needed a solid heart

Here's how you could make a filled heart with the current set:

```html
<style>
.filled {
  fill: currentColor;
}
</style>

<i data-feather="heart" class="filled"></i>
```
*or*
```js
const feather = require('feather-icons')
feather.toSvg('heart', { fill: 'currentColor' })
```

**Comment by knoan** [comment]
>> One of the guiding principles of Feather is that all icons use a 2px stroke with no fill. This creates consistency.

Got the point and agree about the consistency remark. Would slashed icons do (along the lines of https://feathericons.com/node_modules/feather-icons/dist/icons/bell-off.svg)?

**Comment by adsingh14** [comment]
Class '.filled' worked but not with all icons. Take an example of instagram, alert-triangle.
