### ISSUE TITLE
Icon request: text file

### ISSUE THREAD

**Issue by alexantr** [colebemis/feather#23]
Similar to "file" icon.
Possible file name: file-text.svg
Useful for text files in file manager and other places.
Example:
![document-96](https://cloud.githubusercontent.com/assets/4941848/26653758/d899389c-465c-11e7-9f3c-4392bcd72944.png)

**Comment by colebemis** [comment]
Just to clarify, the only difference from `file` would be the horizontal lines?

**Comment by alexantr** [comment]
Yes
