### ISSUE TITLE
Export Variation: Icon Font

### ISSUE THREAD

**Issue by kurisubrooks** [colebemis/feather#29]
I think it'd be a great idea if we could export to a couple font files that are usable on the web, instead of using svg files individually.

**Comment by colebemis** [comment]
I'd be open to this if we can find a clean way to automatically build the font files from the `icons` directory.

**Comment by oakfang** [comment]
How about using [svgicons2svgfont](https://www.npmjs.com/package/svgicons2svgfont)?

**Comment by colebemis** [comment]
@oakfang Do you know how svgicons2svgfont handles SVG `stroke`?

**Comment by oakfang** [comment]
A check shows that multiple font libs have issues with the feather svgs. I found a nice CLI tool that aggregates all web font types [here](https://www.npmjs.com/package/svg2fonts). Maybe it's my Windows machine, though. Maybe try and have a look as well? :)

**Comment by Swizz** [comment]
Could be partially solved with the implementation of #47.

**Comment by colebemis** [comment]
Let's move this conversation to #101 👍
