### ISSUE TITLE
Icon Request: GitHub Icon

### ISSUE THREAD

**Issue by gautamkrishnar** [colebemis/feather#33]
![https://www.iconfinder.com/data/icons/octicons/1024/mark-github-256.png](https://www.iconfinder.com/data/icons/octicons/1024/mark-github-256.png)

**Comment by colebemis** [comment]
Added to the `v2.2.0` branch (https://github.com/colebemis/feather/blob/v2.2.0/icons/logos/github.svg) :octocat:

**Comment by gautamkrishnar** [comment]
👍
