### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by synapticism** [colebemis/feather#35]
This icon set looks fantastic but it doesn't seem to have been published to npm despite the presence of a `package.json`. Unfortunately `feather` is already taken... and it would appear as if someone forked this repo and published an old version as `feather-icon` ([see here](https://github.com/tanshiqi/feather-icon)) but renaming the package to `feather-icons` and [publishing to npm](https://docs.npmjs.com/getting-started/publishing-npm-packages) should work fine.

**Comment by colebemis** [comment]
Thanks for the suggestion! I just changed the name to `feather-icons` and published it (https://www.npmjs.com/package/feather-icons). 

I plan to make the npm package more useful in the future but for now `npm install feather-icons` should work just fine.

**Comment by synapticism** [comment]
Awesome, that was fast!
