### ISSUE TITLE
Expose icons as react components

### ISSUE THREAD

**Issue by timolins** [colebemis/feather#41]
I would love to use these icons in my React projects – beeing able to import them as a component would make this so much fun to use. Maybe `feather` can be added to [react-icons](https://github.com/gorangajic/react-icons) (it already does this, but for other icon libraries)?

Let me know your thoughts on this! 🤔

**Comment by colebemis** [comment]
I think eventually it might make sense to create a `react-feather` repo for this purpose. Maybe `vue-feather`, `jekyll-feather`, etc. repos as well. Just an idea.

**Comment by timolins** [comment]
Indeed. I would also recommend keeping the `feather` repo as barebones as possible.
The only thing I would ad in this repo is the way it exposes all icons.

Finding a better way to expose all icons inside the NPM package would make the development of those packages a lot easier...

For example: 
```js
import heart from 'feather-icons/heart'
// or
import {heart} from 'feather-icons'
```

The current approach isn't really convinient:
```js
import logo from 'feather-icons/icons/core/heart.svg'
```

I'm not sure if it works this way with the webpack loader,  but it would make it much more enjoyable to consume. It even would work in a variety of different frameworks, which makes the other repos less important.

**Comment by Swizz** [comment]
Iam also wondered if this is good to keep the website stuffs into the main repository.

Is feather already ready to be an Orga ? :tada:

**Comment by colebemis** [comment]
@timolins I 100% agree. Let's definitely explore that idea!!

@Swizz I think it makes sense to separate the website from the main Feather repo. If we do something like @timolins is suggesting, the website could just have 'feather' as a dependency.

I like the idea of making Feather a GitHub Org.

**Comment by colebemis** [comment]
I know GitHub's Octicons do something similar to what @timolins is suggesting. We might be able to get some idea from them. 

I really like the idea of keeping the main 'feather' repo as bare bones as possible: just a folder of SVGs and some JS to expose icon information.

**Comment by colebemis** [comment]
We can create additional repos that leverage the main npm package to cover differ use cases.

**Comment by colebemis** [comment]
Here's a nice article from GitHub about how they're using SVGs: https://github.com/blog/2112-delivering-octicons-with-svg

**Comment by colebemis** [comment]
This is almost exactly what I want to do with the main feather repo: https://github.com/jxnblk/geomicons-open

**Comment by Swizz** [comment]
How about closing all issues talking about the same subject to open a Fresh new one referencing them ?

I think we met a consensus about : 
* Making Feather an Org
* Opening all icons as individual svg files
* Providing a SVG Symbole sprite
* Supplying some JS loaders :
  * JS
  * React
  * Vue

**Comment by Swizz** [comment]
We can also dive into multi-packages/mono-repo if you want to keep Feather under your personal profile.

* https://staltz.com/setting-up-a-javascript-monorepo.html
* https://medium.com/@bebraw/the-case-for-monorepos-907c1361708a
* https://lernajs.io/

**Comment by colebemis** [comment]
Let's move this conversation to #101 👍
