### ISSUE TITLE
Icon request: Notification (on/off)

### ISSUE THREAD

**Issue by zslabs** [colebemis/feather#45]
- Notification (on/off)
- Desktop notifications, in-app updates, etc.

<img width="407" alt="screen shot 2017-06-02 at 12 08 33 pm" src="https://cloud.githubusercontent.com/assets/1018402/26734524/61d6476e-478c-11e7-8c30-ad6dbc960ba4.png">

**Comment by kurisubrooks** [comment]
![image](https://cloud.githubusercontent.com/assets/6291467/26734563/ddecd3c0-4801-11e7-8090-8c0fdd6a1700.png)

Hi, we already have these icons under the names seen in the image above.
Thanks

**Comment by zslabs** [comment]
Oof, my bad 👎

Maybe a suggestion for the site would be a way to filter the icons with some sort of search mechanism that would do a quick filter on any tags attached to each icon. Thanks!

**Comment by kurisubrooks** [comment]
We have plans to somehow "alias" icons with a build system, so in the future `bell` will also be shown as `notification` on the website.

**Comment by kurisubrooks** [comment]
This tag system might be a better idea though... Less work.
What do you think @colebemis?

**Comment by zslabs** [comment]
Nice! A suggestion for a quick frontend solution would be a library like http://listjs.com/

**Comment by colebemis** [comment]
@zslabs Wow! Thanks for sharing. That looks really promising. 

I've thought about tags a lot. I think it's a great idea! The only downside is that it would require us to maintain a JSON file with information about every icon. But as feather grows, a giant JSON file might be unavoidable. I wish there was a way to add a tagging system and keep the `icons` directory as the single source of truth.
