### ISSUE TITLE
Icon request: Full-star

### ISSUE THREAD

**Issue by NikolajGilstroem** [colebemis/feather#48]
Full-star icon, so that the star can be used for ratings (3 full stars, followed by 2 empty stars (already in the pack) to show a rating of 3/5)

![starratings](https://cloud.githubusercontent.com/assets/16057281/26746352/ea0363d8-47e6-11e7-9b97-8aef7cb1b25e.png)

**Comment by kurisubrooks** [comment]
![image](https://cloud.githubusercontent.com/assets/6291467/26746596/e55db304-4833-11e7-9a91-0bd40163bca0.png)![image](https://cloud.githubusercontent.com/assets/6291467/26746598/eacdac9a-4833-11e7-8cd5-874fdb502996.png)![image](https://cloud.githubusercontent.com/assets/6291467/26746601/f05b25a2-4833-11e7-93a2-aa3767eae126.png)

Submitted to #46

**Comment by alexantr** [comment]
They are using filling. Is that good?

**Comment by kurisubrooks** [comment]
No, I realised it wasn't such a good idea when I saw how broken it looked on the site....
![image](https://cloud.githubusercontent.com/assets/6291467/26750971/0bdc3e72-4872-11e7-8710-ac997b9a2814.png)

Not sure how to get around this though..... @colebemis

**Comment by alexantr** [comment]
Maybe replace filling with some hatching?

**Comment by colebemis** [comment]
One of the guiding principles of Feather is that all icons use a 2px stroke with no fill. This creates consistency. Having a filled star would break this pattern and wouldn't fit in with the rest of the set. For that reason, I don't think it's a good idea to add it.

That being said, I realize that there are valid use cases for a filled star. The good news is that SVGs are very flexible and can be used in a variety of ways. It wouldn't be hard for anyone to add a `fill` to the star outline if they needed a solid star ⭐️

**Comment by alexantr** [comment]
@colebemis what about star with vertical line for possibility to fill half of it?

**Comment by colebemis** [comment]
I think that would be a little cluttered and probably wouldn't convey the idea very clearly. I think a half star only makes sense when using fills.

**Comment by adirzoari** [comment]
> One of the guiding principles of Feather is that all icons use a 2px stroke with no fill. This creates consistency. Having a filled star would break this pattern and wouldn't fit in with the rest of the set. For that reason, I don't think it's a good idea to add it.
> 
> That being said, I realize that there are valid use cases for a filled star. The good news is that SVGs are very flexible and can be used in a variety of ways. It wouldn't be hard for anyone to add a `fill` to the star outline if they needed a solid star ⭐️

how to add 'fill' to star outline? can you give example?

**Comment by locness3** [comment]
> > One of the guiding principles of Feather is that all icons use a 2px stroke with no fill. This creates consistency. Having a filled star would break this pattern and wouldn't fit in with the rest of the set. For that reason, I don't think it's a good idea to add it.
> > That being said, I realize that there are valid use cases for a filled star. The good news is that SVGs are very flexible and can be used in a variety of ways. It wouldn't be hard for anyone to add a `fill` to the star outline if they needed a solid star ⭐️
> 
> how to add 'fill' to star outline? can you give example?

For a web project, copy-paste the svg file code that you can download on feathericons.com directly to your web page. Then, edit the code by replacing none (in "" after fill) with currentColor. This way, the icon will have a color fill with the color assigned to the CSS `color` property.
![edited file screenshot](https://user-images.githubusercontent.com/37651007/52493841-c29e7c80-2bcc-11e9-9724-a90a5e12cf7c.png)
The modified part is highlighted in this screenshot using the star file.

**Comment by adirzoari** [comment]
@locness3  for react native project can i fill also? with[ react-native-vector-icons? ](https://github.com/oblador/react-native-vector-icons)

**Comment by locness3** [comment]
> @locness3 for react native project can i fill also? with[ react-native-vector-icons? ](https://github.com/oblador/react-native-vector-icons)

idk sorry

**Comment by colebemis** [comment]
@adirzoari Looks like react-native-vector-icons converted Feather to an icon font which means you **cannot** edit the SVG code. I'm sure there there's a react native library that uses SVG instead of fonts.

Here's how you can create a filled star with `react-feather`: https://codesandbox.io/s/n44ykznwwj

**Comment by quedicesebas** [comment]
In Angular I did this:

```
i-feather {
  &.filled svg {
    fill: currentColor;
  }
}
```

and `<i-feather name="star" class="filled text-yellow-500"></i-feather>`
