### ISSUE TITLE
Icon request: Outdoor Icons

### ISSUE THREAD

**Issue by vizFlux** [colebemis/feather#49]
Icons such as camping, hiking, diving, etc.

![6d3d5b25dc3e3192e60e48b7a9add6e1](https://cloud.githubusercontent.com/assets/13939164/26750197/87379a6c-484f-11e7-95c1-b83c2fea4794.jpg)

![outdooricons-flat](https://cloud.githubusercontent.com/assets/13939164/26750205/a501b410-484f-11e7-95be-6c53bb66b9c2.png)

**Comment by colebemis** [comment]
Do you have any specific icons in mind? It'd be super helpful if you could create separate GitHub issues for the icons you need. That way it's easier to tell when an issue can be closed.

**Comment by vizFlux** [comment]
Apologise for the vague description. You may close this and I am more than happy to open a new issue with specific request. Thanks!
