### ISSUE TITLE
Icon request: stop sign (road sign)

### ISSUE THREAD

**Issue by alexantr** [colebemis/feather#50]
Icon with text "STOP" in octagon.
For restricted areas.

![240px-stop_sign_light_red svg](https://cloud.githubusercontent.com/assets/4941848/26751335/6140370c-483f-11e7-80cf-d3c9640da487.png)

**Comment by colebemis** [comment]
I think the `octagon` icon would work well for this use case (https://github.com/colebemis/feather/blob/master/icons/core/octagon.svg). When we implement a tagging system, we can add a `stop` tag to `octagon`.
