### ISSUE TITLE
Icon request: GitHub

### ISSUE THREAD

**Issue by KathrynBrusewitz** [colebemis/feather#57]
For representing a link to a GitHub repo, profile, etc.

An outline of Octocat would fit in nicely with the rest of the icon set:

![github-iconsketch](https://cloud.githubusercontent.com/assets/9070190/26751951/db2d68c8-47f9-11e7-888b-59ab4b29d7a2.png)

**Comment by colebemis** [comment]
Actually just added a `github` icon to the `v2.2.0` branch (https://github.com/colebemis/feather/blob/v2.2.0/icons/logos/github.svg) :octocat:
