### ISSUE TITLE
Star icon

### ISSUE THREAD

**Issue by colmtuite** [colebemis/feather#6]
Star icons are very commonly used in UI design for starring items like Gmail emails, Trello cards etc. or for review ratings like AirBnb etc.

I'd attach a screenshot of Gmail and Trello but it seems that Github doesn't support image upload...?!

**Comment by colebemis** [comment]
Feather already has a star icon :) https://github.com/colebemis/feather/blob/master/icons/star.svg

Also, dragging and dropping any image into the text box should upload the image.

**Comment by colmtuite** [comment]
Oh...my bad!

Ok that's enough annoying you for one day. Carry on making awesome icons, I'm absoutely loving this set!

**Comment by colebemis** [comment]
Ha ha ha. You're not annoying me at all! I appreciated all the feedback. I want Feather to be a community project.

Please keep annoying me 😄
