### ISSUE TITLE
Facebook icon should be a square

### ISSUE THREAD

**Issue by mariomka** [colebemis/feather#63]
Facebook logo isn't the ``f`` letter, is the square with the letter. I think it can be designed like the following:
![Facebook outline logo](http://www.freeiconspng.com/uploads/facebook-outline-transparent--24.png)

**Comment by colebemis** [comment]
This was the logo I had planned to make originally. However, this version of the Facebook logo doesn't work well within the constraints of Feather. The outside box must be 20x20 which makes the "f" too small. Feather's Facebook logo is still easily recognizable and works within the constraints of the set.

**Comment by mariomka** [comment]
It's a pity :(. Thank you for you response!

I'll close the issue.
