### ISSUE TITLE
استقرار به @Hesam555bot

### ISSUE THREAD

**Issue by parham2** [colebemis/feather#65]
> If you'd like to request an icon, please provide the following information:
> - icon name
> - at least one use case
> - screenshots of similar icons
>
> Please create one issue for each icon request.

**Comment by parham2** [comment]
استقرار داده شود به ربات آتنا

**Comment by colebemis** [comment]
This seems like spam

**Comment by parham2** [comment]
نه این مقوله ای بود که از قبل گفتگو در موردش  داشتیم و  کمی متد های بومی نگری را در دستور کار بود اما مسائلی پشت هم مجال تصمیم قاطع نداد
