### ISSUE TITLE
Calendar icon

### ISSUE THREAD

**Issue by MunifTanjim** [colebemis/feather#7]
_**Icon Name**:_ Calendar
_**Use Case**:_ Calendar icon can be used on buttons to create an event. Or it can indicate the publish date of a blog post.
_**Screenshot**:_ The following screenshot is from FontAwesome icons.

![calendariconfontawesome](https://cloud.githubusercontent.com/assets/8050659/26218409/b07f91b0-3c2c-11e7-8554-a930715b2c5f.png)

Anyway, thanks for this awesome iconset. :smiley: I love the minimalist look. :+1:

**Comment by colebemis** [comment]
Added ✅ https://github.com/colebemis/feather/blob/master/icons/calendar.svg
