### ISSUE TITLE
I would like a swastika symbol to be added to your web page because it is a very useful icon. It would look like this - 卐.

### ISSUE THREAD

**Issue by Domozor** [colebemis/feather#71]
> If you'd like to request an icon, please provide the following information:
> - icon name
> - at least one use case
> - screenshots of similar icons
>
> Please create one issue for each icon request.

**Comment by colebemis** [comment]
This issue is in direct violation of the [Code of Conduct](https://github.com/colebemis/feather/blob/master/CODE_OF_CONDUCT.md). I will not tolerate the use of any hateful language or symbols. This violation has been reported to GitHub.
