### ISSUE TITLE
Shopping Cart and/or Bag

### ISSUE THREAD

**Issue by iamtravjohnson** [colebemis/feather#79]
> If you'd like to request an icon, please provide the following information:
> - icon name: "Cart" or "Bag" 
> - at least one use case: Used on e-commerce websites as a button for users to access their cart (both options would be great but are used for the same thing).
> - screenshots of similar icons: 2 screenshots attached
![screen shot 2017-06-06 at 7 50 19 am](https://cloud.githubusercontent.com/assets/4359597/26827854/07278478-4a8d-11e7-9f1d-301ed5e38ffe.png)
![screen shot 2017-06-06 at 7 50 44 am](https://cloud.githubusercontent.com/assets/4359597/26827853/072559c8-4a8d-11e7-8e66-a7f90ffb032d.png)
> Please create one issue for each icon request.

**Comment by cassiewallace** [comment]
I second this!
