### ISSUE TITLE
Missing film.svg from zip file/assets

### ISSUE THREAD

**Issue by chrismessina** [colebemis/feather#88]
I noticed that you have an icon for Film on feathericons.com but it's missing from the zip file and in the icons/ directory. Just an FYI!

**Comment by colebemis** [comment]
@chrismessina Hmm, I just tried downloading the zip from feathericons.com and I found `film.svg` in `icons/photo-and-video`. Would you mind trying again to see if it's still missing?

**Comment by chrismessina** [comment]
Yooo that's so weird! It's not in this file list:

![image](https://user-images.githubusercontent.com/22610/26866756-73b412de-4b17-11e7-9297-bd8799996310.png)

...ohhhh. I was looking in the [wrong repo](https://github.com/colebemis/feather/tree/gh-pages/icons). My bad!

**Comment by colebemis** [comment]
Haha, no worries! Don't hesitate to create another issue if you find something wrong or have an icon request 😃
