### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by alexantr** [colebemis/feather#9]
It would be nice to use bower package.

**Comment by colebemis** [comment]
What are some use cases where this would be helpful? 

FYI, it looks like Bower is actually recommending people use yarn and webpack instead of Bower. (https://bower.io/)

**Comment by alexantr** [comment]
I'm not front-end developer and aren't using this trendy tools. I'm working with Yii and it uses bower packages. I can manually download this package, but always want to have last version with one command in terminal.

**Comment by mistermantas** [comment]
Use npm *and* Bower. New projects ditch Bower and most have npm anyway.

**Comment by alexantr** [comment]
Ok, will use npm.
