### ISSUE TITLE
License is not in line with your intentions

### ISSUE THREAD

**Issue by vitorgalvao** [colebemis/feather#95]
[In the README, you state](https://github.com/colebemis/feather#license) (emphasis mine):

> Feather is released under the [MIT License](http://opensource.org/licenses/MIT). In short, you are free to use Feather in any personal, open-source or commercial work. **Attribution is optional but appreciated**.

However, that goes *counter* to the MIT License. With the MIT License, attribution is not optional. If you look at [the page for your posted license](https://github.com/colebemis/feather/blob/gh-pages/LICENSE), Github even describes the license at the top.

![image](https://user-images.githubusercontent.com/1699443/26888193-2c93e236-4ba2-11e7-959d-d4a89adf9650.png)

So it cannot be done both ways. To keep the MIT License, the note about attribution being optional should be removed. But if you want to keep attribution optional you should consider another license, such as [The Unlicense](https://choosealicense.com/licenses/unlicense/). It has no conditions.

**Comment by colebemis** [comment]
Thanks for letting me know! I've updated the README. Please let me know if you find any more inconsistencies.

**Comment by vitorgalvao** [comment]
I’m a bit surprised, though. Why keep the MIT license if you were fine about not having attribution? Wouldn’t releasing into the public domain be more in line with your initial goal?

**Comment by colebemis** [comment]
@vitorgalvao I haven't given it too much thought yet. For now, I'll keep the MIT license because it seems to be the Open Source standard. I'm definitely considering The Unlicense though. Thanks for sending that to me!

**Comment by vitorgalvao** [comment]
In case that eases your mind a bit, The Unlicense is also supported by Github automatically. It’s one of the options when you start a new repo.

**Comment by fuzzy76** [comment]
As far as I can tell, using a handful of these icons on a website is not a "substantial portions of" this project, so most of the license would not apply in that case any way?

**Comment by balibebas** [comment]
As the OP suggests an unconditional license is desirable for users. The MIT notice condition requires copying the license terms, notice and copyright line into works using the icons which isn't usually ideal. Here's another unconditional license you could consider:

https://choosealicense.com/licenses/0bsd/

And some relevant conversation occurring right now on HN:

https://news.ycombinator.com/item?id=20503612
